In [2]:
import numpy as np

In [4]:
np.__version__

'1.20.3'

In [5]:
a = np.array([1,2,3,4])

In [6]:
a

array([1, 2, 3, 4])

In [7]:
print(a)

[1 2 3 4]


In [8]:
a.dtype

dtype('int32')

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
a.itemsize

4

In [13]:
a.tolist()

[1, 2, 3, 4]

In [14]:
c=np.array([1,2,3])

In [15]:
c

array([1, 2, 3])

In [16]:
print(c)

[1 2 3]


In [17]:
d=np.array([1,2,3])

In [18]:
c is d #똑같은 numpy가 아님

False

In [21]:
e = np.asarray(c)

In [22]:
c is e

True

In [23]:
f = c.copy()

In [25]:
c is f

False

In [27]:
import pandas as pd

In [31]:
s = pd.Series([1,2,3,4], index=list('abcd'))

In [32]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [33]:
print(s)

a    1
b    2
c    3
d    4
dtype: int64


In [35]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [36]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
s.ndim

1

In [39]:
s.shape

(4,)

In [40]:
s.size

4

In [41]:
s['a']

1

In [42]:
s['d']

4

In [43]:
s['a':'c']

a    1
b    2
c    3
dtype: int64

In [44]:
s[:]

a    1
b    2
c    3
d    4
dtype: int64

In [45]:
s[:-1]

a    1
b    2
c    3
dtype: int64

In [49]:
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]], index=list('ab'), columns=list('abcd'))

In [50]:
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8